site_name: Daemon Docs

nav:
   - Home: index.md
   - Markdown Guide: markdown.md
   - MySQL Statistics: mysql_statistic.md
   - User Operator: users_operator.md
   - Git Learning: Git_training_Agenda.md
   - gitLearnBranching: LearnGitBranching.md
theme:  readthedocs
